
CREATE TABLE USER (
  ID SERIAL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE GROUP (
  ID SERIAL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE USER_GROUP (
  USER_ID INTEGER NOT NULL,
  GROUP_ID INTEGER NOT NULL,
  SINCE DATE NOT NULL,
  PRIMARY KEY(USER_ID, GROUP_ID),
  FOREIGN KEY(USER_ID)
    REFERENCES USUARIO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(GRUPO_ID)
    REFERENCES GRUPO(ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


